/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 cuteCat.gltf
Author: Fayme Wong (https://sketchfab.com/FaymeWong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-cat-d06965e6712646328129388b32c47b96
Title: Cute Cat
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function CuteCat(props) {
  const { nodes, materials } = useGLTF(
    "app/3DComponents/cute_cat/cuteCat.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.defaultMat_0}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.defaultMat}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_5}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.material_1}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("app/3DComponents/cute_cat/cuteCat.gltf");
