/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 cat.gltf
Author: artofaria (https://sketchfab.com/artofaria)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cat-7e8cbcad506041dc9c3a0cb74edb3360
Title: cat
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Cat(props) {
  const { nodes, materials } = useGLTF("app/3DComponents/cat/cat.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.006"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/cat.gltf");
