/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 taurus.gltf
Author: voguart (https://sketchfab.com/voguart)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/taurus-f5f52ec6f2c741a2a3fe2d9146a2c1a3
Title: Taurus
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Taurus(props) {
  const { nodes, materials } = useGLTF("app/3DComponents/taurus/taurus.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.002"]}
        position={[0.38, 0.424, 2.91]}
        rotation={[1.734, 0.373, 0.07]}
        scale={[0.207, 0.146, 0.147]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.001"]}
        position={[0, 0.028, 2.067]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.defaultMat}
        position={[0, -0.125, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("app/3DComponents/taurus/taurus.gltf");
